orbs:
  php: circleci/php@1.1.0
  codecov: codecov/codecov@3.2.4
version: 2.1
workflows:
  test:
    jobs:
      - php/test:
          version: "8.1"
          post-steps:
            - codecov/upload